name: flutter_aula_1
description: PI - 5 Semestre

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  provider: ^6.0.3
  shared_preferences: ^2.1.1
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0

  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.4.0
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_calendar: ^20.3.57
  flip_card: ^0.6.0
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  flutter_launcher_icons: ^0.11.0
  auto_size_text: ^3.0.0
  validatorless: ^1.2.3
  firebase_storage: ^11.2.1
  flutter_pdfview: ^1.3.1
  path: ^1.8.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/logo-pi.png
    - images/clock-icon-removebg-preview.png

flutter_icons:
  android: true
  ios: true
  image_path: images/clock-icon.png
