// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQ9aiP_zDoW7HoMpcjluB9wXrNATX-3M',
    appId: '1:489890668957:web:7ab2485a7ed72c92bd0f74',
    messagingSenderId: '489890668957',
    projectId: 'pi-to-do-list',
    authDomain: 'pi-to-do-list.firebaseapp.com',
    storageBucket: 'pi-to-do-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWtqX62yvQ87cpCI4-_VXi0Gjrygi4u2I',
    appId: '1:489890668957:android:88e634fe155d5207bd0f74',
    messagingSenderId: '489890668957',
    projectId: 'pi-to-do-list',
    storageBucket: 'pi-to-do-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAeye835JWkDbtNPgYlKxJVpp2HXGEfPM',
    appId: '1:489890668957:ios:e149c8ff2f20dea1bd0f74',
    messagingSenderId: '489890668957',
    projectId: 'pi-to-do-list',
    storageBucket: 'pi-to-do-list.appspot.com',
    iosClientId: '489890668957-o2ut66nnt91vamssd6bmh993h2s41tl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAula1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAeye835JWkDbtNPgYlKxJVpp2HXGEfPM',
    appId: '1:489890668957:ios:e149c8ff2f20dea1bd0f74',
    messagingSenderId: '489890668957',
    projectId: 'pi-to-do-list',
    storageBucket: 'pi-to-do-list.appspot.com',
    iosClientId: '489890668957-o2ut66nnt91vamssd6bmh993h2s41tl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAula1',
  );
}
